from decimal import Decimal

from django.test import TestCase
from django.utils import translation

from .models import League, Product, Size, Team


class ProductModelTests(TestCase):
    def setUp(self):
        self.league = League.objects.create(name_ru="РПЛ", name_en="RPL")
        self.team = Team.objects.create(name_ru="Зенит", name_en="Zenit", league=self.league)
        self.product = Product.objects.create(
            title_ru="Домашняя джерси Зенит", title_en="Zenit Home Jersey",
            team=self.team, league=self.league, season="2024/25", size=Size.L,
            description_ru="Описание", description_en="Description",
            price=Decimal("6990.00"), stock=5,
        )

    def test_slug_autogenerated(self):
        self.assertTrue(self.product.slug)

    def test_in_stock_flag(self):
        self.assertTrue(self.product.in_stock)
        self.product.stock = 0
        self.assertFalse(self.product.in_stock)

    def test_bilingual_title_picks_language(self):
        with translation.override("ru"):
            self.assertEqual(self.product.title, "Домашняя джерси Зенит")
        with translation.override("en"):
            self.assertEqual(self.product.title, "Zenit Home Jersey")

    def test_english_falls_back_to_russian_when_empty(self):
        self.product.title_en = ""
        with translation.override("en"):
            self.assertEqual(self.product.title, "Домашняя джерси Зенит")
