# Generated by Django 5.0.6 on 2026-06-09 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('russian_post', 'Почта России'), ('cdek', 'СДЭК'), ('boxberry', 'Boxberry'), ('yandex', 'Яндекс.Доставка'), ('pony', 'Pony Express'), ('dellin', 'Деловые Линии')], max_length=32, unique=True)),
                ('name_ru', models.CharField(max_length=80, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='Название (EN)')),
                ('eta_days_min', models.PositiveSmallIntegerField(default=2, verbose_name='Срок, дней (от)')),
                ('eta_days_max', models.PositiveSmallIntegerField(default=7, verbose_name='Срок, дней (до)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Способ доставки',
                'verbose_name_plural': 'Способы доставки',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, help_text='Пусто = правило по умолчанию для всех регионов', max_length=120, verbose_name='Регион')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость, ₽')),
                ('free_above', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Бесплатно при сумме от, ₽')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='shipping.shippingmethod')),
            ],
            options={
                'verbose_name': 'Тариф доставки',
                'verbose_name_plural': 'Тарифы доставки',
                'unique_together': {('method', 'region')},
            },
        ),
    ]
