# Generated by Django 5.0.6 on 2026-06-09 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=120, verbose_name='Лига (RU)')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='Лига (EN)')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Лига',
                'verbose_name_plural': 'Лиги',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название (RU)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Название (EN)')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('season', models.CharField(help_text='например 2024/25', max_length=20, verbose_name='Сезон')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=4, verbose_name='Размер')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена, ₽')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Остаток')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.league')),
            ],
            options={
                'verbose_name': 'Джерси',
                'verbose_name_plural': 'Джерси',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/')),
                ('alt_ru', models.CharField(blank=True, max_length=150)),
                ('alt_en', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=120, verbose_name='Команда (RU)')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='Команда (EN)')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='catalog.league')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['name_ru'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.team'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['team', 'league', 'size'], name='catalog_pro_team_id_7a7306_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='catalog_pro_price_2d2a4c_idx'),
        ),
    ]
