# Generated by Django 5.0.6 on 2026-06-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('club', 'Клубные'), ('country', 'Сборные')], default='club', help_text='Клубная джерси или джерси сборной', max_length=10, verbose_name='Категория'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='catalog_pro_categor_50f92a_idx'),
        ),
    ]
