# Generated by Django 5.0.6 on 2026-06-09 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.league'),
        ),
        migrations.AlterField(
            model_name='product',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.team'),
        ),
    ]
