# Generated by Django 5.0.6 on 2026-06-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_league_alter_product_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Сборная/страна (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_ru',
            field=models.CharField(blank=True, max_length=120, verbose_name='Сборная/страна (RU)'),
        ),
    ]
